
// This file has been generated by the GUI designer. Do not modify.
namespace FiveInRow
{
	public partial class ConfigGameWindow
	{
		private global::Gtk.VBox vbox14;

		private global::Gtk.Frame frame;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox15;

		private global::Gtk.HBox hbox4;

		private global::Gtk.RadioButton rbAi;

		private global::Gtk.RadioButton rbMultiplayer;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.Label labelBordSize;

		private global::Gtk.SpinButton sbBoardSize;

		private global::Gtk.Label GtkLabel2;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Alignment alignment17;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Alignment alignment19;

		private global::Gtk.Button btnPlay;

		private global::Gtk.Alignment alignment18;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget FiveInRow.ConfigGameWindow
			this.Name = "FiveInRow.ConfigGameWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Game Configurarion");
			this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			// Container child FiveInRow.ConfigGameWindow.Gtk.Container+ContainerChild
			this.vbox14 = new global::Gtk.VBox();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.frame = new global::Gtk.Frame();
			this.frame.Name = "frame";
			this.frame.BorderWidth = ((uint)(15));
			// Container child frame.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox15 = new global::Gtk.VBox();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.rbAi = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("AI (Artificial Intelligence)"));
			this.rbAi.CanFocus = true;
			this.rbAi.Name = "rbAi";
			this.rbAi.DrawIndicator = true;
			this.rbAi.UseUnderline = true;
			this.rbAi.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.hbox4.Add(this.rbAi);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.rbAi]));
			w1.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.rbMultiplayer = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Multiplayer (online)"));
			this.rbMultiplayer.CanFocus = true;
			this.rbMultiplayer.Name = "rbMultiplayer";
			this.rbMultiplayer.DrawIndicator = true;
			this.rbMultiplayer.UseUnderline = true;
			this.rbMultiplayer.Group = this.rbAi.Group;
			this.hbox4.Add(this.rbMultiplayer);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.rbMultiplayer]));
			w2.Position = 1;
			this.vbox15.Add(this.hbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.hbox4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.labelBordSize = new global::Gtk.Label();
			this.labelBordSize.Name = "labelBordSize";
			this.labelBordSize.LabelProp = global::Mono.Unix.Catalog.GetString("Select board size: ");
			this.fixed4.Add(this.labelBordSize);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.labelBordSize]));
			w4.Y = 5;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.sbBoardSize = new global::Gtk.SpinButton(8D, 25D, 1D);
			this.sbBoardSize.CanFocus = true;
			this.sbBoardSize.Name = "sbBoardSize";
			this.sbBoardSize.Adjustment.PageIncrement = 10D;
			this.sbBoardSize.ClimbRate = 1D;
			this.sbBoardSize.Numeric = true;
			this.sbBoardSize.UpdatePolicy = ((global::Gtk.SpinButtonUpdatePolicy)(1));
			this.sbBoardSize.Value = 8D;
			this.fixed4.Add(this.sbBoardSize);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.sbBoardSize]));
			w5.X = 116;
			this.vbox15.Add(this.fixed4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.fixed4]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.GtkAlignment.Add(this.vbox15);
			this.frame.Add(this.GtkAlignment);
			this.GtkLabel2 = new global::Gtk.Label();
			this.GtkLabel2.Name = "GtkLabel2";
			this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Game Mode</b>");
			this.GtkLabel2.UseMarkup = true;
			this.frame.LabelWidget = this.GtkLabel2;
			this.vbox14.Add(this.frame);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.frame]));
			w9.Position = 0;
			// Container child vbox14.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.alignment17 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment17.Name = "alignment17";
			this.hbox5.Add(this.alignment17);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.alignment17]));
			w10.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.alignment19 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment19.Name = "alignment19";
			// Container child alignment19.Gtk.Container+ContainerChild
			this.btnPlay = new global::Gtk.Button();
			this.btnPlay.CanFocus = true;
			this.btnPlay.Name = "btnPlay";
			this.btnPlay.UseUnderline = true;
			this.btnPlay.Label = global::Mono.Unix.Catalog.GetString("PLAY");
			this.alignment19.Add(this.btnPlay);
			this.vbox5.Add(this.alignment19);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.alignment19]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox5.Add(this.vbox5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox5]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.alignment18 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment18.Name = "alignment18";
			this.hbox5.Add(this.alignment18);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.alignment18]));
			w14.Position = 2;
			this.vbox14.Add(this.hbox5);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.hbox5]));
			w15.Position = 2;
			this.Add(this.vbox14);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 589;
			this.DefaultHeight = 395;
			this.Show();
		}
	}
}
