
// This file has been generated by the GUI designer. Do not modify.
namespace FiveInRow
{
	public partial class ConfigGameWindow
	{
		private global::Gtk.VBox vboxMain;

		private global::Gtk.Frame frame;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox15;

		private global::Gtk.HBox hbox4;

		private global::Gtk.RadioButton rbAi;

		private global::Gtk.RadioButton rbMultiplayer;

		private global::Gtk.Fixed fixed4;

		private global::Gtk.Label labelBordSize;

		private global::Gtk.SpinButton sbBoardSize;

		private global::Gtk.Label lbPlayerName;

		private global::Gtk.Entry entryName;

		private global::Gtk.HBox hboxButtons;

		private global::Gtk.Alignment alignment3;

		private global::Gtk.Button btnServerShow;

		private global::Gtk.Alignment alignment5;

		private global::Gtk.Button btnClientShow;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Label GtkLabel4;

		private global::Gtk.Frame frameServer;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label lbIpServer;

		private global::Gtk.Entry entryIpServer;

		private global::Gtk.Label lbPortServer;

		private global::Gtk.Entry entryPortServer;

		private global::Gtk.Button btnStartServer;

		private global::Gtk.Label GtkLabel6;

		private global::Gtk.Frame frameClient;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label lbIpClient;

		private global::Gtk.Entry entryIpClient;

		private global::Gtk.Label lbPortClient;

		private global::Gtk.Entry entryPortClient;

		private global::Gtk.Button btnConnectClient;

		private global::Gtk.Label GtkLabel7;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Alignment alignment17;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Alignment alignment19;

		private global::Gtk.Button btnPlay;

		private global::Gtk.Alignment alignment18;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget FiveInRow.ConfigGameWindow
			this.Name = "FiveInRow.ConfigGameWindow";
			this.Title = global::Mono.Unix.Catalog.GetString("Game Configurarion");
			this.Icon = global::Stetic.IconLoader.LoadIcon(this, "gtk-apply", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.AllowShrink = true;
			// Container child FiveInRow.ConfigGameWindow.Gtk.Container+ContainerChild
			this.vboxMain = new global::Gtk.VBox();
			this.vboxMain.Name = "vboxMain";
			this.vboxMain.Spacing = 6;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.frame = new global::Gtk.Frame();
			this.frame.Name = "frame";
			this.frame.BorderWidth = ((uint)(15));
			// Container child frame.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox15 = new global::Gtk.VBox();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.rbAi = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("AI (Artificial Intelligence)"));
			this.rbAi.CanFocus = true;
			this.rbAi.Name = "rbAi";
			this.rbAi.DrawIndicator = true;
			this.rbAi.UseUnderline = true;
			this.rbAi.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.hbox4.Add(this.rbAi);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.rbAi]));
			w1.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.rbMultiplayer = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Multiplayer (online)"));
			this.rbMultiplayer.CanFocus = true;
			this.rbMultiplayer.Name = "rbMultiplayer";
			this.rbMultiplayer.DrawIndicator = true;
			this.rbMultiplayer.UseUnderline = true;
			this.rbMultiplayer.Group = this.rbAi.Group;
			this.hbox4.Add(this.rbMultiplayer);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.rbMultiplayer]));
			w2.Position = 1;
			this.vbox15.Add(this.hbox4);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.hbox4]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.fixed4 = new global::Gtk.Fixed();
			this.fixed4.Name = "fixed4";
			this.fixed4.HasWindow = false;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.labelBordSize = new global::Gtk.Label();
			this.labelBordSize.Name = "labelBordSize";
			this.labelBordSize.LabelProp = global::Mono.Unix.Catalog.GetString("Select board size: ");
			this.fixed4.Add(this.labelBordSize);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.labelBordSize]));
			w4.Y = 5;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.sbBoardSize = new global::Gtk.SpinButton(8D, 25D, 1D);
			this.sbBoardSize.CanFocus = true;
			this.sbBoardSize.Name = "sbBoardSize";
			this.sbBoardSize.Adjustment.PageIncrement = 10D;
			this.sbBoardSize.ClimbRate = 1D;
			this.sbBoardSize.Numeric = true;
			this.sbBoardSize.UpdatePolicy = ((global::Gtk.SpinButtonUpdatePolicy)(1));
			this.sbBoardSize.Value = 8D;
			this.fixed4.Add(this.sbBoardSize);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.sbBoardSize]));
			w5.X = 105;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.lbPlayerName = new global::Gtk.Label();
			this.lbPlayerName.Name = "lbPlayerName";
			this.lbPlayerName.LabelProp = global::Mono.Unix.Catalog.GetString("Name: ");
			this.fixed4.Add(this.lbPlayerName);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.lbPlayerName]));
			w6.X = 189;
			w6.Y = 5;
			// Container child fixed4.Gtk.Fixed+FixedChild
			this.entryName = new global::Gtk.Entry();
			this.entryName.CanFocus = true;
			this.entryName.Name = "entryName";
			this.entryName.IsEditable = true;
			this.entryName.InvisibleChar = '●';
			this.fixed4.Add(this.entryName);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed4[this.entryName]));
			w7.X = 231;
			this.vbox15.Add(this.fixed4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.fixed4]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hboxButtons = new global::Gtk.HBox();
			this.hboxButtons.Name = "hboxButtons";
			this.hboxButtons.Spacing = 6;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.hboxButtons.Add(this.alignment3);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.alignment3]));
			w9.Position = 0;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.btnServerShow = new global::Gtk.Button();
			this.btnServerShow.CanFocus = true;
			this.btnServerShow.Name = "btnServerShow";
			this.btnServerShow.UseUnderline = true;
			this.btnServerShow.Label = global::Mono.Unix.Catalog.GetString("SERVER");
			this.hboxButtons.Add(this.btnServerShow);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.btnServerShow]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.hboxButtons.Add(this.alignment5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.alignment5]));
			w11.Position = 2;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.btnClientShow = new global::Gtk.Button();
			this.btnClientShow.CanFocus = true;
			this.btnClientShow.Name = "btnClientShow";
			this.btnClientShow.UseUnderline = true;
			this.btnClientShow.Label = global::Mono.Unix.Catalog.GetString("CLIENT");
			this.hboxButtons.Add(this.btnClientShow);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.btnClientShow]));
			w12.Position = 3;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hboxButtons.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.hboxButtons.Add(this.alignment1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hboxButtons[this.alignment1]));
			w13.Position = 4;
			this.vbox15.Add(this.hboxButtons);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.hboxButtons]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.GtkAlignment.Add(this.vbox15);
			this.frame.Add(this.GtkAlignment);
			this.GtkLabel4 = new global::Gtk.Label();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Game Mode</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame.LabelWidget = this.GtkLabel4;
			this.vboxMain.Add(this.frame);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.frame]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.frameServer = new global::Gtk.Frame();
			this.frameServer.Name = "frameServer";
			this.frameServer.BorderWidth = ((uint)(15));
			// Container child frameServer.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.lbIpServer = new global::Gtk.Label();
			this.lbIpServer.Name = "lbIpServer";
			this.lbIpServer.LabelProp = global::Mono.Unix.Catalog.GetString("IP: ");
			this.hbox9.Add(this.lbIpServer);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.lbIpServer]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.entryIpServer = new global::Gtk.Entry();
			this.entryIpServer.CanFocus = true;
			this.entryIpServer.Name = "entryIpServer";
			this.entryIpServer.IsEditable = true;
			this.entryIpServer.InvisibleChar = '●';
			this.hbox9.Add(this.entryIpServer);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.entryIpServer]));
			w19.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.lbPortServer = new global::Gtk.Label();
			this.lbPortServer.Name = "lbPortServer";
			this.lbPortServer.LabelProp = global::Mono.Unix.Catalog.GetString("Port: ");
			this.hbox9.Add(this.lbPortServer);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.lbPortServer]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.entryPortServer = new global::Gtk.Entry();
			this.entryPortServer.CanFocus = true;
			this.entryPortServer.Name = "entryPortServer";
			this.entryPortServer.IsEditable = true;
			this.entryPortServer.InvisibleChar = '●';
			this.hbox9.Add(this.entryPortServer);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.entryPortServer]));
			w21.Position = 3;
			// Container child hbox9.Gtk.Box+BoxChild
			this.btnStartServer = new global::Gtk.Button();
			this.btnStartServer.CanFocus = true;
			this.btnStartServer.Name = "btnStartServer";
			this.btnStartServer.UseUnderline = true;
			this.btnStartServer.Label = global::Mono.Unix.Catalog.GetString("   START   ");
			this.hbox9.Add(this.btnStartServer);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.btnStartServer]));
			w22.Position = 4;
			w22.Expand = false;
			w22.Fill = false;
			this.GtkAlignment1.Add(this.hbox9);
			this.frameServer.Add(this.GtkAlignment1);
			this.GtkLabel6 = new global::Gtk.Label();
			this.GtkLabel6.Name = "GtkLabel6";
			this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString("<b>SERVER</b>");
			this.GtkLabel6.UseMarkup = true;
			this.frameServer.LabelWidget = this.GtkLabel6;
			this.vboxMain.Add(this.frameServer);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.frameServer]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.frameClient = new global::Gtk.Frame();
			this.frameClient.Name = "frameClient";
			this.frameClient.BorderWidth = ((uint)(15));
			// Container child frameClient.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.lbIpClient = new global::Gtk.Label();
			this.lbIpClient.Name = "lbIpClient";
			this.lbIpClient.LabelProp = global::Mono.Unix.Catalog.GetString("IP: ");
			this.hbox10.Add(this.lbIpClient);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.lbIpClient]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.entryIpClient = new global::Gtk.Entry();
			this.entryIpClient.CanFocus = true;
			this.entryIpClient.Name = "entryIpClient";
			this.entryIpClient.IsEditable = true;
			this.entryIpClient.InvisibleChar = '●';
			this.hbox10.Add(this.entryIpClient);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.entryIpClient]));
			w27.Position = 1;
			// Container child hbox10.Gtk.Box+BoxChild
			this.lbPortClient = new global::Gtk.Label();
			this.lbPortClient.Name = "lbPortClient";
			this.lbPortClient.LabelProp = global::Mono.Unix.Catalog.GetString("Port: ");
			this.hbox10.Add(this.lbPortClient);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.lbPortClient]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.entryPortClient = new global::Gtk.Entry();
			this.entryPortClient.CanFocus = true;
			this.entryPortClient.Name = "entryPortClient";
			this.entryPortClient.IsEditable = true;
			this.entryPortClient.InvisibleChar = '●';
			this.hbox10.Add(this.entryPortClient);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.entryPortClient]));
			w29.Position = 3;
			// Container child hbox10.Gtk.Box+BoxChild
			this.btnConnectClient = new global::Gtk.Button();
			this.btnConnectClient.CanFocus = true;
			this.btnConnectClient.Name = "btnConnectClient";
			this.btnConnectClient.UseUnderline = true;
			this.btnConnectClient.Label = global::Mono.Unix.Catalog.GetString("CONNECT");
			this.hbox10.Add(this.btnConnectClient);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.btnConnectClient]));
			w30.Position = 4;
			w30.Expand = false;
			w30.Fill = false;
			this.GtkAlignment2.Add(this.hbox10);
			this.frameClient.Add(this.GtkAlignment2);
			this.GtkLabel7 = new global::Gtk.Label();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString("<b>CLIENT</b>");
			this.GtkLabel7.UseMarkup = true;
			this.frameClient.LabelWidget = this.GtkLabel7;
			this.vboxMain.Add(this.frameClient);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.frameClient]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vboxMain.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.alignment17 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment17.Name = "alignment17";
			this.hbox5.Add(this.alignment17);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.alignment17]));
			w34.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.alignment19 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment19.Name = "alignment19";
			// Container child alignment19.Gtk.Container+ContainerChild
			this.btnPlay = new global::Gtk.Button();
			this.btnPlay.CanFocus = true;
			this.btnPlay.Name = "btnPlay";
			this.btnPlay.UseUnderline = true;
			this.btnPlay.Label = global::Mono.Unix.Catalog.GetString("PLAY");
			this.alignment19.Add(this.btnPlay);
			this.vbox5.Add(this.alignment19);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.alignment19]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			this.hbox5.Add(this.vbox5);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox5]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.alignment18 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment18.Name = "alignment18";
			this.hbox5.Add(this.alignment18);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.alignment18]));
			w38.Position = 2;
			this.vboxMain.Add(this.hbox5);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vboxMain[this.hbox5]));
			w39.Position = 3;
			this.Add(this.vboxMain);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 520;
			this.DefaultHeight = 378;
			this.Show();
		}
	}
}
